Repository oasisprotocol/nexus, pull requests merged in 2022-10, with the labels that each got.

#157 Add mitjat to code owners
  .github/CODEOWNERS
Labels: infrastructure

#155 Improve Docker dev and e2e test
  config/docker-dev.yml
  docker-compose.yml
  tests/e2e/e2e_test.go
Labels: bug, testing

#141 Emerald: import parsing from nexus
  analyzer/emerald/emerald.go
  analyzer/emerald/incoming.go
  analyzer/uncategorized/addresses.go
  analyzer/uncategorized/eth.go
  analyzer/uncategorized/evm_raw_tx.go
  analyzer/uncategorized/evm_raw_tx_test.go
  analyzer/uncategorized/geth_sender_pub.go
  analyzer/uncategorized/helpers.go
  analyzer/uncategorized/quantities.go
  analyzer/uncategorized/runtimes.go
  analyzer/uncategorized/visitors.go
  go.mod
  go.sum
  storage/migrations/0011_emerald_incoming.up.sql
Labels: analysis-layer

#163 API: Improve latest Indexer status documentation
  api/spec/v1.yaml
  storage/client/client.go
Labels: documentation, api-layer

#187 Add Docker workflow comment
  .github/workflows/docker-indexer.yaml
Labels: documentation

#191 Update e2e tests documentation
  .github/workflows/ci-test.yaml
  Makefile
  tests/README.md
  tests/e2e/README.md
Labels: documentation, testing, tooling
