Repository oasisprotocol/nexus, pull requests merged in 2023-04, with the labels that each got.

#372 api: Fix runtime accounts query
  storage/client/client.go
  storage/client/queries/queries.go
Labels: bug, good first issue, api-layer, p2

#374 bugfix: db: Allow NULL tx body (for malformed txs)
  api/spec/v1.yaml
  storage/migrations/02_runtimes.up.sql
Labels: bug, analysis-layer

#384 Update API endpoint description
  api/spec/v1.yaml
Labels: documentation, api-layer
