Repository oasisprotocol/nexus, pull requests merged in 2023-07, with the labels that each got.

#474 bump grpc to v1.53.0
  go.mod
  go.sum
Labels: bug, analysis-layer, dependencies

#480 analyzer/evm: handle downloading ERC-721 mutable data
  analyzer/runtime/evm/client.go
Labels: bug, analysis-layer

#473 Andrew7234/stress test
  .gitignore
  tests/load/README.md
  tests/load/locust.conf
  tests/load/locustfile.py
Labels: testing
