Repository oasisprotocol/nexus, pull requests merged in 2023-06, with the labels that each got.

#438 tests: don't run tests concurrently
  Makefile
Labels: testing

#440 runtime: error message does not need to be a valid utf-8
  analyzer/runtime/runtime.go
  storage/api.go
  storage/api_test.go
Labels: analysis-layer

#441 evmtokens: check for nil EVMTokenMutableData
  analyzer/evmtokens/evm_tokens.go
Labels: bug, analysis-layer

#444 storage: read token name
  storage/client/queries/queries.go
Labels: bug, api-layer
